package com.rrm.parking.audit.enums;

public enum TypeActionAudit {
    AUTHENTIFICATION_REUSSIE,
    AUTHENTIFICATION_ECHOUEE,

    CREATION,
    CONSULTATION,
    MODIFICATION,
    VALIDATION,
    REFUS,
    ANNULATION,
    ARCHIVAGE,

    IMPRESSION,
    ACTIVATION,
    SUSPENSION,
    DESACTIVATION,

    TELEVERSEMENT_DOCUMENT,
    TELECHARGEMENT_DOCUMENT,

    EXPORT,
    IMPORT,
    MIGRATION
}