services:
  # 1. Interface web phpMyAdmin connectée en DIRECT à TiDB Cloud
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: rrm-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: gateway01.eu-central-1.prod.aws.tidbcloud.com
      PMA_PORT: 4000
      PMA_USER: 2wc4nHiW6bLvdfS.root
      PMA_PASSWORD: MbkMZvpObv0CSmHy
      PMA_SSL: "true"
      UPLOAD_LIMIT: 64M
    ports:
      - "8080:80"

  # 2. Backend API Spring Boot connecté en DIRECT à TiDB Cloud
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rrm-backend
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://gateway01.eu-central-1.prod.aws.tidbcloud.com:4000/rrm_db?sslMode=VERIFY_IDENTITY
      SPRING_DATASOURCE_USERNAME: 2wc4nHiW6bLvdfS.root
      SPRING_DATASOURCE_PASSWORD: MbkMZvpObv0CSmHy
      RRM_TARIFF_INIT_ENABLED: "false"
      RRM_BOOTSTRAP_ENABLED: "false"
      RRM_JWT_SECRET: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
      RRM_STORAGE_PATH: /app/storage
    volumes:
      - backend_storage:/app/storage

  # 3. Frontend SPA React & Nginx Reverse Proxy
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rrm-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  backend_storage:
    name: rrm_backend_storage
