package com.rrm.parking.security.enums;

public enum CodePermission {
    UTILISATEUR_CONSULTER,
    UTILISATEUR_CREER,
    UTILISATEUR_MODIFIER,
    UTILISATEUR_BLOQUER,
    UTILISATEUR_DESACTIVER,

    ROLE_ATTRIBUER,
    ROLE_RETIRER,

    PARKING_AFFECTER_AGENT,
    PARKING_RETIRER_AGENT,

    AUDIT_SECURITE_CONSULTER
}
