package com.rrm.parking.security.enums;

public enum CodeRole {
    AGENT_ADMINISTRATIF,
    SUPERVISEUR,
    RESPONSABLE_STATIONNEMENT,
    COMPTABLE,
    RESPONSABLE_REPORTING,
    ADMINISTRATEUR_SI,
    DIRECTION_GENERALE,
    VICE_RESPONSABLE
}
