package com.rrm.parking.notification.enums;

public enum TypeNotification {
    DEMANDE_CREEE,
    DEMANDE_VALIDEE,
    DEMANDE_REFUSEE,

    PAIEMENT_CONFIRME,
    CHEQUE_REJETE,

    FACTURE_DISPONIBLE,

    CARTE_DISPONIBLE,
    CARTE_ACTIVEE,
    CARTE_SUSPENDUE,
    CARTE_DESACTIVEE,

    RENOUVELLEMENT_PROCHE,
    ABONNEMENT_EXPIRATION_J10,
    ABONNEMENT_EXPIRATION_J5,
    ABONNEMENT_EXPIRE
}
