package com.rrm.parking.document.enums;

public enum TypePieceJointe {
    CIN_RECTO,
    CIN_VERSO,

    CARTE_GRISE_RECTO,
    CARTE_GRISE_VERSO,

    JUSTIFICATIF_DOMICILE,

    REGISTRE_COMMERCE,
    ICE,
    ATTESTATION_ENTREPRISE,

    CONTRAT_SIGNE,

    COPIE_CHEQUE,
    JUSTIFICATIF_PAIEMENT,

    AUTRE,

    FACTURE_SIGNEE,
    DECHARGE_REMISE_CORPORATE
}